### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by bluesun08** [igorpecovnik/Cubietruck-Debian#35]
Sorry, i'm a newbie.
Cubietruck - Hummingboard - banana pi: Are there any board recommendations with regard to performance?

**Comment by igorpecovnik** [comment]
Banana PI and Cubietruck and all other A20 boards are similar in performance. It depend for what you want to use them? Hummingboard (dual or quad core pro version) is better in all cases but it's lack of SATA port. OK, you can buy msata to sata extender or simply use mSata SSD drive which really rocks.

**Comment by bluesun08** [comment]
Thank you for answer. I want to setup a home server with samba, squid, asterisk, nginx, cups, openvpn, sane, etc. similar to your micro server (http://www.igorpecovnik.com/2013/12/10/micro-home-server/). Do you recommend Hummingboard for this or any other board on the huge smb-market?

**Comment by igorpecovnik** [comment]
Huh. It's hard to decide :) I am running such set-up still on Cubietruck and even with the cheapest possible option in A20 range - Olimex Lime or Banana - it would work good enough for SOHO style operations. Humminboard is expensier and give more power and options. Check Udoo boards too. Similar hw - currently I don't have personal experiences. Note one thing - power consumption / heat is higher with iMx6 / Hummingboard / Uddo boards. If you put them on heavy load, fan could be needed and some boards are already equipped with it :)

**Comment by bluesun08** [comment]
Again many thanks for your thoughts. So now i think i know my preferences:
I want a sbc which is a compromise between performance and moderate cpu temperature. Sata (or Sata adapter) and Gbit-LAN is obligatory.
What are your recommendations?
