### ISSUE TITLE
No initramfs?

### ISSUE THREAD

**Issue by BackSlasher** [igorpecovnik/Cubietruck-Debian#36]
Forgive me if I'm wrong, but I'm under the impression the built image does not contain `initramfs`, and therefor doesn't allow booting from a drive by its `UUID`.
Is it on purpose?

**Comment by igorpecovnik** [comment]
No it doesn't since it's almost no need, but it can be added. I never used on sunxi so I don't know if it's working properly.

**Comment by BackSlasher** [comment]
I already worked around it but was curious as to why it's missing. Is it the norm in Cubie/ARM builds?
Could you point me on the easiest way to add it to the build (e.g. what config file to modify)?

**Comment by igorpecovnik** [comment]
I would start here:
http://linux-sunxi.org/Initial_Ramdisk
https://wiki.ubuntu.com/Initramfs

The sunxi manual should be o.k. for classic u-boot but we are not there any more so the answer might not be this simple. Without reading and testing I don't know.
