### ISSUE TITLE
Noob question - How to build u-boot and kernel only in order to update existing running board (Cubieboard2)

### ISSUE THREAD

**Issue by berturion** [igorpecovnik/Cubietruck-Debian#37]
Hello and many thanks for you work.
I have a question. I own a Cubieboard2, rootfs is Debian wheezy  (Cubieez) on SATA and my board boots from NAND (the kernel is on /dev/nand1) partition. I wanted to try last mainline kernel 3.19 but I saw that NAND is not supported yet.
And I thought about using your script to build and package it but I am not sure how to do this.
How can I use your script to prepare a SD-Card with the u-boot and kernel it builds ?
Does your script prepare /lib/firmware and /lib/modules for existing rootfs ?
Thanks from Reunion Island.

**Comment by igorpecovnik** [comment]
Yes, my build script prepares / creates everything - uboot, kernel with modules and headers, some basic firmware pack, rootfs, sata+nand install script, auto expand script,  ... I would say it's more useful stuff than in other compilations. Output is: bootable SD image. If you fail with creation grab latest prepared image from my blog.

BTW, mainline kernel will need some time to get to the functional level of kernel 3.4.x.

**Comment by berturion** [comment]
OK, great. I am currently running it, I will browse the ouputs. I know that mainline kernel is not as functional as 3.4.x but I am very curious, I want to test it.
Thanks !

**Comment by berturion** [comment]
Closine issue, answer given.
