### ISSUE TITLE
Add link to old archives

### ISSUE THREAD

**Issue by kenhys** [igorpecovnik/Cubietruck-Debian#42]
Currently, there is no link to some old version of archives such as v2.9 for 3.4.105 kernel on http://www.igorpecovnik.com/2013/12/24/cubietruck-debian-wheezy-sd-card-image/.

It is good enough to recommend latest version, but it is inconvenient when there is some issue such as WiFi issue and so on. For example, it seems that v3.2 for 3.4.105 kernel doesn't work well for my cubietruck,  so I'm happy if there are links to old archives on that page because I can try old ones instead.

**Comment by igorpecovnik** [comment]
One archive is: http://mirror.igorpecovnik.com or this http://cubie.nobrainz.de/ which is even older. I am planning to fix all issues asap. I think I already detect the source of problem.

**Comment by kenhys** [comment]
Thanks! I didn't know it.
