### ISSUE TITLE
firstrun fails

### ISSUE THREAD

**Issue by vihai** [igorpecovnik/Cubietruck-Debian#45]
Hi, on a fresh .106 installation I found systemd in a degraded state because firstrun crashed not finding disable_led.sh

root@cubieboard2:~# systemctl status
● cubieboard2
    State: degraded
     Jobs: 0 queued
   Failed: 1 units

I commented out disable_led.sh, restarted the firstrun service and it completed fine.

**Comment by igorpecovnik** [comment]
Thanks for report - fixed in scripts but need to rebuild images.
