### ISSUE TITLE
Booting with eth0 disconnected prevents DHCP client from running afterwist

### ISSUE THREAD

**Issue by vihai** [igorpecovnik/Cubietruck-Debian#47]
Hi Igor,

Is your image anything different with regard to Jessie's networking.service unit and/or dhclient?

If not I'm going to report this issue directly to Debian.

Anyway, the issue is the following:

1- Power on the cubieboard2 with ethernet cable disconnected
2- Let the DHCP client timeout
3- Connect the cable
4- The DHCP client does not detect the link state change and the interface remains forever without an IP address

**Comment by igorpecovnik** [comment]
This is normal behavior with simple network setup. We can't declare this as a bug.

For advanced networking (with certain limitations too) you need to use different package: https://wiki.debian.org/NetworkManager

**Comment by vihai** [comment]
Hi, no, it's not normal behaviour. A DHCP client must continue forever to obtain an IP address and never give up (at most it should lower the requests frequency).

In my scenario, which is all but uncommon, the switch to which the cubieboard is connected has a long boot time and in case of power failure the cubieboard loses connectivity forever. It IS a bug.

Please keep this bug open until the dhcp client maintainers fix this issue.

**Comment by igorpecovnik** [comment]
If we declare this as a bug than this is a Debian bug. Simple networking is not capable to handle this kind of exception at least not by default / that I am aware of. I think you need to fix this with some workaround - Network manager is probably the cleanest one.
