### ISSUE TITLE
Difference between 3.4.105-cubieboard and default ARM kernel

### ISSUE THREAD

**Issue by jacksgt** [igorpecovnik/Cubietruck-Debian#48]
Hi Igor,

first of all: I'm really sorry I had to create an 'Issue' for this question, but I did not see another option to contact you.

I wanted to know what the difference between the 3.4.105-cubieboard kernel (your kernel) and the default ARM kernel in Debian Jessie repositories (currently 3.16).
Could I just install the default kernel?

**Comment by igorpecovnik** [comment]
3.16 is (probably) usable on Cubieboard but it has very limited functionality - check here: http://linux-sunxi.org/Linux_mainlining_effort or my blog where you can find more details - benefits and step back for each kernel.

You need to get at least 3.19.x or rather use (not existing with default Debian) kernel 3.4.x where everything works. Easy switching between old and new is possible only on my Debian, on official you won't be able to use (old) new + old kernel this easy ... to see which is best for what you want to do. 3.19 is good for server usage and for light desktop - no acceleration, but is stable. With 3.16 you probably have only serial output.

Summary: stay away from default kernel at this point.

**Comment by jacksgt** [comment]
Thank you for the explanation.

I was mainly interested in Kernel 4.0 (and above) because of the Live Patching feature.

**Comment by dan-and** [comment]
Hi,

As long as you don’t need NAND support and 3d/2d acceleration, you should be 
fine with the Kernel 4.0 code.

**Comment by jacksgt** [comment]
@dan-and 
What a pitty, I'm running my system on the NAND :/
Thanks for the input!

**Comment by dan-and** [comment]
Well, switching to micro-sd should be the easiest step, but thats another topic.
