### ISSUE TITLE
Enable Battery Support

### ISSUE THREAD

**Issue by RafaelKa** [igorpecovnik/Cubietruck-Debian#49]
i use Wheezy image and realized now, that there is no support for power management.

directory `/sys/class/power_supply/` is empty :/

**Comment by igorpecovnik** [comment]
That's normal if you use new kernel 3.18 + 

But we have a solution:
http://learn.linksprite.com/pcduino/pcduino-hardware-basic-and-improve/axp209-battery-info-with-a-script/

I am working on my script to give a little more precise output and will be implemented soon.

In kernel 3.4.107 is and should be present.

**Comment by RafaelKa** [comment]
in http://learn.linksprite.com/pcduino/pcduino-hardware-basic-and-improve/axp209-battery-info-with-a-script/ for cubietruck are charge/discharge inverted

**Comment by RafaelKa** [comment]
[here is a script(WIP) for power_supply](https://gist.github.com/RafaelKa/ecbaca4db4d792032f2a)

if you want, then you can include it to your build somewhere

**Comment by igorpecovnik** [comment]
I already made a script but it's not working properly. It shows me that battery is enabled even if it is not. 
http://forum.armbian.com/index.php/topic/45-battery/?hl=battery

I made a little progress on this but the bug remains.

How is your script doing?

**Comment by RafaelKa** [comment]
Didn't gat exactly what you mean.
There are properties: 
[ACIN](https://gist.github.com/RafaelKa/ecbaca4db4d792032f2a#file-power_supply-sh-L25)
[BATTERY_CONSUMPTION](https://gist.github.com/RafaelKa/ecbaca4db4d792032f2a#file-power_supply-sh-L50)
[BATTERY_CHARGING](https://gist.github.com/RafaelKa/ecbaca4db4d792032f2a#file-power_supply-sh-L81)
[BATTERY_CONNECTED](https://gist.github.com/RafaelKa/ecbaca4db4d792032f2a#file-power_supply-sh-L86)
[BATTERY_NOT_FULL](https://gist.github.com/RafaelKa/ecbaca4db4d792032f2a#file-power_supply-sh-L101)

You must properly combine this properties with && to get it working.

**Comment by igorpecovnik** [comment]
I had some issues with new kernel on Cubietruck. I'll check if your scripts show correct value for:

BATTERY_CONNECTED = 0

I always got an value of 1

Within kernel 3.4. it's working fine.

**Comment by RafaelKa** [comment]
also on 4.2 my script has same problem with BATTERY_CONNECTED

**Comment by RafaelKa** [comment]
It seems to be setting by REG 32H, which is currently 0x00 by default on 4.2
[i2cset -y -f 0 0x34 0x32 0x42](https://gist.github.com/RafaelKa/ecbaca4db4d792032f2a#file-power_supplyv002-sh-L15-L16) seemst to resolve this problem

**Comment by morriswinkler** [comment]
What happened to the kernel module from 3.4, is it still lying around to be ported to 4.11?

**Comment by igorpecovnik** [comment]
battery support exists in modern kernel since some time, but it does not provide all info as found in legacy kernel.
