### ISSUE TITLE
4.1.X runs only on single core?

### ISSUE THREAD

**Issue by RafaelKa** [igorpecovnik/Cubietruck-Debian#52]
it's true?

**Comment by igorpecovnik** [comment]
yes, if you haven't upgrade the boot loader.

**Comment by RafaelKa** [comment]
which package is it?
linux-u-boot-cubietruck or linux-u-boot-cubietruck-next?
by last upgrade or dist-upgrade i have seen upgrade from linux-u-boot-cubietruck
and now system says: "linux-u-boot-cubietruck is already the newest version" by `apt-get install linux-u-boot-cubietruck`

**Comment by RafaelKa** [comment]
so i installed now 
`apt-get install linux-jessie-root-next-cubietruck linux-u-boot-cubietruck-next`
but didn't find dtb package for cubietruck are dtb's package contents in linux-jessie-root-next-cubietruck?

**Comment by igorpecovnik** [comment]
Uboot is unique for each board while dtb is linked to kernel. This is the correct package:

linux-dtb-next-sunxi
