### ISSUE TITLE
Change Cubieboard A20 -> Banana Pi 

### ISSUE THREAD

**Issue by norrest** [igorpecovnik/Cubietruck-Debian#57]
Hi! 
I have finished the assembly for Cubieboard A20 with its own settings.
I want to use it for the second board Banana Pi
In the folder / boot script.bin I changed the link (/boot/bin/bananapipro.bin)  but the board  is not loaded!
I do not want to completely assemble a new system for the second card!
How to be?

**Comment by norrest** [comment]
```
ext4load mmc 0 0x49000000 /boot/dtb/${fdtfile} || fatload mmc 0 0x49000000 /dtb/${fdtfile} || ext4load mmc 0 0x49000000 /dtb/${fdtfile}
ext4load mmc 0 0x46000000 /boot/zImage || fatload mmc 0 0x46000000 zImage || ext4load mmc 0 0x46000000 zImage
env set fdt_high ffffffff
bootz 0x46000000 - 0x49000000
```

These settings are the same

**Comment by igorpecovnik** [comment]
You need to use boot loader for Banana and script.bin, the rest is the same.

**Comment by norrest** [comment]
`You need to use boot loader for Banana`

How?

**Comment by igorpecovnik** [comment]
you need to compile or download it, then write to the card. Try one of those:
http://apt.armbian.com/pool/main/l/linux-u-boot-bananapi/

If you install a package on running system it will update boot loader on that sd card. You can extract it and burn to the sd card this way, where /dev/sdX is device of your SD card. Check twice before executing this, that you are writing to right device.

`dd if=u-boot-sunxi-with-spl.bin of=/dev/sdX bs=1024 seek=8`

**Comment by norrest** [comment]
yet another thank you very much !!!
