### ISSUE TITLE
usb high speed lost after reboot

### ISSUE THREAD

**Issue by norrest** [igorpecovnik/Cubietruck-Debian#58]
```
[    4.541270] hub 4-0:1.0: USB hub found
[    4.985079] usb 4-1: new full-speed USB device number 2 using ohci-platform
[    5.184176] usb 4-1: New USB device found, idVendor=20b1, idProduct=2012
[    5.190970] usb 4-1: New USB device strings: Mfr=1, Product=3, SerialNumber=0
```

but before 
`
   94.800701] usb 2-1: new high-speed USB device number 3 using ehci-platform

`
tested on cubieboarda20 and banana pi 

The problem manifests itself, if reboot system with connected device. 
When turn on detected correctly! after reboot - goin to full-speed

[    5.234120] usb 4-1: new full-speed USB device number 2 using ohci-platform
[    5.409175] usb 4-1: not running at top speed; connect to a high speed hub

**Comment by norrest** [comment]
I am satisfied, if you help with reset command (USB reinitialization) device!

**Comment by igorpecovnik** [comment]
I have no idea.

**Comment by norrest** [comment]
rmmod phy_sun4i_usb
rmmod: ERROR: Module phy_sun4i_usb is in use

modprobe -rv phy_sun4i_usb
modprobe: FATAL: Module phy_sun4i_usb is in use.

**Comment by norrest** [comment]
Very interesting
I try use this utils
https://raw.githubusercontent.com/heiher/hubpower/master/hubpower.c 
And after 

`./hubpower 1:1 power 1 off 1 on
./hubpower 2:1 power 1 off 1 on
./hubpower 3:1 power 1 off 1 on
./hubpower 4:1 power 1 off 1 on

./hubpower 1:1 bind
./hubpower 2:1 bind
./hubpower 3:1 bind
./hubpower 4:1 bind
`

`
[ 1424.800662] hub 3-0:1.0: USB hub found
[ 1424.945457] usb 2-1: new high-speed USB device number 5 using ehci-platform
[ 1426.356728] hub 4-0:1.0: USB hub found
[ 1426.721465] usb 4-1: new full-speed USB device number 4 using ohci-platform
[ 1426.923526] usb 4-1: New USB device found, idVendor=20b1, idProduct=2012
[ 1426.930268] usb 4-1: New USB device strings: Mfr=1, Product=3, SerialNumber=0
`

speed lost 

to full-speed USB
