### ISSUE TITLE
Headphones volume problem 

### ISSUE THREAD

**Issue by norrest** [igorpecovnik/Cubietruck-Debian#59]
Hi! 
I install  ARMBIAN Debian GNU/Linux 8 (jessie) 4.6.3-sunxi 
Cubieboard a20 

But sound going only from R-channel with congestion, because the impression that the dual (left and right)

aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sun4icodec [sun4i-codec], device 0: CDC PCM Codec-0 []
  Subdevices: 0/1
  Subdevice #0: subdevice #0

 amixer
Simple mixer control 'Left Mixer Left DAC',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'Power Amplifier',0
  Capabilities: volume volume-joined
  Playback channels: Mono
  Capture channels: Mono
  Limits: 0 - 63
  Mono: 24 [38%] [-39.00dB]
Simple mixer control 'Power Amplifier DAC',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'Power Amplifier Mixer',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'Power Amplifier Mute',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'Right Mixer Left DAC',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'Right Mixer Right DAC',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]

Using alsamixer  i can change total level of volume 

I try to install new alsa-utils,  alsa-tools, libasound2 - do not help 

speaker-test -c 2

speaker-test 1.1.1

Playback device is default
Stream parameters are 48000Hz, S16_LE, 2 channels
Using 16 octaves of pink noise
Rate set to 48000Hz (requested 48000Hz)
Buffer size range from 128 to 131072
Period size range from 64 to 16384
Using max buffer size 131072
Periods = 4
was set period_size = 16384
was set buffer_size = 131072
 0 - Front Left
 1 - Front Right
Time per period = 2.749069
 0 - Front Left
 1 - Front Right
Time per period = 5.461570
 0 - Front Left
 1 - Front Right
Time per period = 5.462427
 0 - Front Left
 1 - Front Right
Time per period = 5.462540
 0 - Front Left
 1 - Front Right
Time per period = 5.462528
 0 - Front Left
^C 1 - Front Right
Time per period = 2.273033

speaker-test I hear only one channel (

**Comment by norrest** [comment]
I try to use 
http://mirror.igorpecovnik.com/Armbian_5.14_Cubieboard2_Debian_jessie_3.4.112.7z
But board on loading turn off !!!!!! Confused)

**Comment by norrest** [comment]
I try to manual compile 5.17 and kernel 3.4.112 - nevermind. On loading turn off

**Comment by igorpecovnik** [comment]
This looks like a bad power supply. Can you try with another one?

**Comment by norrest** [comment]
On old kernel 3.4.96-sun7i+ #2 SMP its ok!

**Comment by igorpecovnik** [comment]
I don't own Cubieboard2, but 1 and 3 :( Can't check. Try this - copy script.bin from working image to our image, place it to /boot/ directory and try booting.

**Comment by miopa** [comment]
@norrest , your alsa mixer settings are wrong, this is how they should be set

```
Simple mixer control 'Left Mixer Left DAC',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'Power Amplifier',0
  Capabilities: volume volume-joined
  Playback channels: Mono
  Capture channels: Mono
  Limits: 0 - 63
  Mono: 55 [87%] [-8.00dB]
Simple mixer control 'Power Amplifier DAC',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'Power Amplifier Mixer',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'Power Amplifier Mute',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'Right Mixer Left DAC',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'Right Mixer Right DAC',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
```

**Comment by norrest** [comment]
https://github.com/igorpecovnik/Cubietruck-Debian/issues/61 in old kernel all work fine

**Comment by ImSugarFree** [comment]
I have the same problem on Banana Pi. How did you sole it?
