### ISSUE TITLE
Turn off during  boot Cubieboard 2 Legacy release

### ISSUE THREAD

**Issue by norrest** [igorpecovnik/Cubietruck-Debian#61]
Hi! 
After few months i try again use Legacy  image version for Cubieboard 2
http://www.armbian.com/cubieboard-2/
http://www.armbian.com/donate/?f=Armbian_5.14_Cubieboard2_Debian_jessie_3.4.112.7z
But during the boot process, the board is turned off!

**Comment by igorpecovnik** [comment]
Can you try with self build image? If you can't compile on your own, I will prepare one or two test images. I don't own a CB2 - we use default u-boot settings. They are sometimes broken or wrong.

**Comment by norrest** [comment]
`[ o.k. ] Copying files to image [ tmprootfs.raw ]
        689.46M  99%   22.36MB/s    0:00:29 (xfr#37655, to-chk=0/47659)

sent 692.38M bytes  received 759.15K bytes  22.73M bytes/sec
total size is 693.34M  speedup is 1.00
[ o.k. ] Copying files to /boot partition [ tmprootfs.raw ]
         16.08M  99%   16.67MB/s    0:00:00 (xfr#43, to-chk=0/47)

sent 16.09M bytes  received 848 bytes  10.72M bytes/sec
total size is 16.08M  speedup is 1.00
[ o.k. ] Free space: [ SD card ]
/dev/loop0p1    1.2G  784M  349M  70% /mnt/USB/output/cache/mount
[ o.k. ] Writing bootloader [ /dev/loop0 ]
[ o.k. ] Done building [ /mnt/USB/output/images/Armbian_5.17_Cubieboard2_Debian_jessie_3.4.112.raw ]
[ o.k. ] Runtime [ 70 min ]
`
NEVERMIND! during the boot process, the board is turned off!

**Comment by norrest** [comment]
Can u told me where i can download armbian for Cubieboarda20 with NAND support kernel ?

**Comment by igorpecovnik** [comment]
OK, than we might have same problem as on Cubieboard 1 ... by using this (unlogical) patch:
https://github.com/igorpecovnik/lib/blob/master/patch/u-boot/u-boot-default/cubieboard1.patch
You need to adjust it for CB2

If this fails, try some older u-boot.

All our 3.4.112 builds supports NAND install.

**Comment by norrest** [comment]
Ok! At 1st i change 
Cubieboard2_defconfig 
./sources/u-boot/v2016.07/configs

`CONFIG_ARM=y
CONFIG_ARCH_SUNXI=y
CONFIG_MACH_SUN7I=y
CONFIG_DRAM_CLK=480
CONFIG_MMC0_CD_PIN="PH1"
CONFIG_DEFAULT_DEVICE_TREE="sun7i-a20-cubieboard2"
# CONFIG_SYS_MALLOC_CLEAR_ON_INIT is not set
CONFIG_SPL=y
CONFIG_SYS_EXTRA_OPTIONS="SUNXI_GMAC,AHCI,SATAPWR=SUNXI_GPB(8)"
# CONFIG_CMD_IMLS is not set
# CONFIG_CMD_FLASH is not set
# CONFIG_CMD_FPGA is not set
CONFIG_ETH_DESIGNWARE=y
CONFIG_CMD_GPIO=y
CONFIG_USB_EHCI_HCD=y
`

RIGHT?

**Comment by norrest** [comment]
Dont help// ( Board is not boot

**Comment by igorpecovnik** [comment]
:( 

Than try with older u-boot. Add:
`BOOTBRANCH="v2016.01"`
to 
`userpatches/lib.config`
And rebuild.

**Comment by norrest** [comment]
How to do this?

**Comment by igorpecovnik** [comment]
Create file lib.config and add there this parameter. This means that old bootloader source will be used for uboot. I know it's a bit complicated but I have other ideas.

**Comment by norrest** [comment]
[ o.k. ] Using user configuration override [ userpatches/lib.config ]
[ o.k. ] Starting Armbian build script [ @host ]
[ o.k. ] Syncing clock [ host ]
[ o.k. ] Downloading sources
[ error ] ERROR in function fetch_from_repo [ general.sh:169 ]
[ error ] Error in configuration
[ o.k. ] Process terminated

**Comment by norrest** [comment]
How to download old u-boot? Where?

**Comment by norrest** [comment]
i download https://github.com/linux-sunxi/u-boot-sunxi and rename it to v2016.07

**Comment by igorpecovnik** [comment]
No, that wont help. Since we are not getting anywhere I prepare two images with different u-boots.

Try in this order:
[http://mirror.igorpecovnik.com/test/U-boot-2016.01-Armbian_5.17_Cubieboard2_Debian_jessie_3.4.112.7z](http://mirror.igorpecovnik.com/test/U-boot-2016.01-Armbian_5.17_Cubieboard2_Debian_jessie_3.4.112.7z)
[http://mirror.igorpecovnik.com/test/U-boot-2015.10-Armbian_5.17_Cubieboard2_Debian_jessie_3.4.112.7z](http://mirror.igorpecovnik.com/test/U-boot-2015.10-Armbian_5.17_Cubieboard2_Debian_jessie_3.4.112.7z)

**Comment by norrest** [comment]
U-boot-2015.10-Armbian_5.17_Cubieboard2_Debian_jessie_3.4.112.7z - WORK!!!!!!
**THANK YOU!!!!!**

**Comment by igorpecovnik** [comment]
Thank you for your time too. Our next CB2 builds will be o.k.
