### ISSUE TITLE
uboot and built-in peripherals

### ISSUE THREAD

**Issue by norrest** [igorpecovnik/Cubietruck-Debian#62]
Hello! Thank you for your excellent work!
I use banana pi board! But since I only need ethernet and USB, I want to ask you whether the problem of the operating system will not boot if I take away from the board plugs hdmi / rca / audio? I plan to remove them together with buffers of chips! 
**Thank you!**

**Comment by igorpecovnik** [comment]
It should boot ... attach serial console to see what's wrong if it doesn't boot. Perhaps this is related: https://forum.armbian.com/index.php/topic/3481-cubieboard-a20-2012-version-does-not-boot-with-armbian-525/

**Comment by norrest** [comment]
Thank you! I yet "in development" - have not tried! Just I plan on doing it!
And the last little question, I understand if resolder memory, with 1 gigabyte to 2 gigabytes, with the boot can be nevertheless a problem!?!
